version: "3"
services:
  altv:
    image: mrlutin/altv-server-beta
    container_name: altv-beta
    volumes:
      - data:/altv-persistend/
    ports:
      - "7788:7788"
      - "7788:7788/udp"
volumes:
  data:
